spring.application.name=property-registration-backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/property_registration_db?useSSL=false&serverTimezone=Asia/Kolkata}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL:false}
spring.jpa.open-in-view=false

server.port=${SERVER_PORT:8080}

app.upload.dir=${UPLOAD_DIR:D:/PropertyRegistrationSystem/demo/uploads}
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:5MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:6MB}
app.jwt.secret=${JWT_SECRET:PropertyRegistrationSystemDemoSecretKey2026SecureJwtKey}
app.jwt.issuer=${JWT_ISSUER:property-registration-system}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
app.frontend.origin=${FRONTEND_ORIGIN:http://localhost:5173}